### ISSUE TITLE
not able to upload results when report contains some chars

### ISSUE THREAD

**Issue by mhajhassan** [gurock/trcli#230]
### TestRail CLI Version

1.9.5

### CLI Environment

macOS

### TestRail Version

8.0.1 Early Access (1029) 

### TestRail Instance Type

Enterprise Server

### Current behavior

while trying to upload the results, I am getting this error:
`Adding results: 0/397
No attachments found to upload.
Field :results contains one or more invalid results (case C815 unknown or not part of the test run)

**** API Call
method: POST
url: https://domain/testrail/index.php?/api/v2/delete_run/254
response status code: 200
response body: b''
****

**** API Call
method: POST
url: https://domain/testrail/index.php?/api/v2/delete_section/290
response status code: 400
response body: {'error': 'Field :section_id is not a valid section.'}
****
Deleted created run
Unable to delete created section: Field :section_id is not a valid section.
`
I checked the sections and also test cases, all exist and correct, and after checking I saw that in request `index.php?/api/v2/add_results_for_cases` I got response code `response status code: 400
response body: {'error': 'Field :results contains one or more invalid results (case C815 unknown or not part of the test run)'}` but the test case is known and a part of the test run, but because it's the first test case of the payload, 

at the end I saw that in TEST-junit-platform-suite.xml we have for one test case the following:
`
<testcase name="testOrderAppraisalWithCreditCardStatusError" classname="test.marketplace.OrderAppraisalTest" time="133" started-at="2024-05-07T03:52:38.479930843" finished-at="2024-05-07T03:54:52.464411986">
	<error message="Expected condition failed: waiting for visibility of [[ChromeDriver: chrome on linux (ad6926b5c1ebdc504961d5ddbedce22a)] -&gt; name: tc-checkbox] (tried for 120 second(s) with 500 milliseconds interval)
Build info: version: '4.16.1', revision: '9b4c83354e'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '6.3.9-arch1-1', java.version: '17.0.11'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 124.0.6367.91, chrome: {chromedriverVersion: 124.0.6367.91 (51df0e5e17a8..., userDataDir: /tmp/.org.chromium.Chromium...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:35667}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: linux, proxy: Proxy(), se:cdp: ws://localhost:35667/devtoo..., se:cdpVersion: 124.0.6367.91, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: ad6926b5c1ebdc504961d5ddbedce22a" type="org.openqa.selenium.TimeoutException"><![CDATA[org.openqa.selenium.TimeoutException: Expected condition failed: waiting for visibility of [[ChromeDriver: chrome on linux (ad6926b5c1ebdc504961d5ddbedce22a)] -> name: tc-checkbox] (tried for 120 second(s) with 500 milliseconds interval)
Build info: version: '4.16.1', revision: '9b4c83354e'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '6.3.9-arch1-1', java.version: '17.0.11'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 124.0.6367.91, chrome: {chromedriverVersion: 124.0.6367.91 (51df0e5e17a8..., userDataDir: /tmp/.org.chromium.Chromium...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:35667}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: linux, proxy: Proxy(), se:cdp: ws://localhost:35667/devtoo..., se:cdpVersion: 124.0.6367.91, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: ad6926b5c1ebdc504961d5ddbedce22a
	at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:84)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:229)
	at objects.pages.BasePage.waitForVisibility(BasePage.java:136)
	at objects.pages.marketplace.PaymentScreenPage.ThenIAcceptTheTermsAndConditions(PaymentScreenPage.java:284)
	at test.marketplace.OrderAppraisalTest.testOrderAppraisalWithCreditCardStatusError(OrderAppraisalTest.java:207)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
]]>	</error>
	<system-out><![CDATA[
unique-id: [engine:junit-platform-suite]/[suite:suites.AllTestsSuite]/[engine:junit-jupiter]/[class:test.marketplace.OrderAppraisalTest]/[method:testOrderAppraisalWithCreditCardStatusError()]
display-name: testOrderAppraisalWithCreditCardStatusError()
]]>	</system-out>
	<system-out><![CDATA[

]]>	</system-out>
	<properties>
		<property name="test_id" value="C726"/>
		<property name="testrail_result_comment" value="1. GivenIAmOnOrderAppraisalPage
2. URL: https://domain.com/order/?product_id=APPRAISAL&amp;language=d
3. acceptCookieSettingsIfShown
4. login using customer: Automated1589804193511
5. setLocalStorage: de-DE
6. WhenIChooseTheDomainToOrderAppraisal
7. domainOrder: automated-appraisal1715053958956.com
8. ThenICheckTheTotalOrderPriceAndFinishMyOrder
9. ThenIAcceptTheTermsAndConditions
"/>
	</properties>
</testcase>
` 
it looks like same issue with ticket https://github.com/gurock/trcli/issues/212

**Comment by bitcoder** [comment]
@mhajhassan 

1) to be able to reproduce the issue, can you please share the report file you used and the exact `trcli` command line?
2) how did you generate the JUnit XML report? Did you use Junit5 together with the testrail-junit-extensions library?

**Comment by mhajhassan** [comment]
@bitcoder 
unfortunately I can't share the file, but yes used Junit5 together with the testrail-junit-extensions and the command was used it :
`trcli -y --insecure -c "trcli-config.yml" parse_junit \
 -f "./target/TEST-junit-jupiter.xml" \
--run-description "description" \
--case-matcher "property" \
--title "title"`

it was working all the time, but we saw that after some failing test cases, saw that it's related to some chars

**Comment by mhajhassan** [comment]
the TEST-junit-jupiter.xml is always generated, I can see it in target folder

**Comment by bitcoder** [comment]
> @bitcoder 
> unfortunately I can't share the file, but yes used Junit5 together with the testrail-junit-extensions and the command was used it :
> `trcli -y --insecure -c "trcli-config.yml" parse_junit \
>  -f "./target/TEST-junit-jupiter.xml" \
> --run-description "description" \
> --case-matcher "property" \
> --title "title"`
> 
> it was working all the time, but we saw that after some failing test cases, saw that it's related to some chars

Without a concrete example to replicate it there isn't much "we" can do

**Comment by acuanico-tr-galt** [comment]
Thank you for reporting this issue. While there hasn’t been recent activity, please know that your feedback has been noted and is helping shape our internal improvements to TR CLI.
 
We’re closing this issue for now due to inactivity, but if this is still a concern or if you have additional details, feel free to reopen or open a new issue at any time.
 
We appreciate your input and support!

**Comment by acuanico-tr-galt** [comment]
Hi @danielkatfavor thanks for reaching out. Can you create a new issue based on the problem you encountered? Thank you!
